/**
 * Hermes hybrid context contract (0.21 alignment):
 *  - AGENTS.md (the file Hermes auto-loads) inlines the CRITICAL rule
 *    directives and the 0.21 subagent context-file note.
 *  - No .hermes.md twin is emitted; previously emitted AIWG twins/pointers
 *    are removed (managed or signature-matched), operator-authored
 *    .hermes.md files are preserved.
 *  - The rule/note text is shared with tools/agents/providers/hermes.mjs —
 *    the sync tests below fail if either copy drifts.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generate,
  HERMES_CRITICAL_RULES,
  HERMES_SUBAGENT_NOTE,
} from '../../../src/smiths/context-pipeline/index.js';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), 'aiwg-hermes-pipeline-'));
}

function seedProject(dir: string): void {
  mkdirSync(join(dir, '.aiwg'), { recursive: true });
  writeFileSync(join(dir, '.aiwg', 'aiwg.config'), JSON.stringify({
    version: '1',
    providers: ['hermes'],
    installed: { sdlc: { version: '2026.8.27', source: 'bundled', installedAt: '2026-09-04T00:00:00.000Z', deployedTo: { hermes: { agents: 0, commands: 0, skills: 107, rules: 0 } } } },
  }, null, 2));
}

describe('Hermes hybrid context contract', () => {
  it('inlines CRITICAL rules and the 0.21 subagent note into AGENTS.md', async () => {
    const dir = makeTmpDir();
    try {
      seedProject(dir);
      const result = await generate({ provider: 'hermes', projectPath: dir, sections: [], detectExistingFiles: true });
      const agentsMd = readFileSync(result.agentsMdPath, 'utf8');
      const ruleHeadings = agentsMd.match(/^### Rule:/gm) ?? [];
      expect(ruleHeadings.length).toBeGreaterThanOrEqual(7);
      expect(agentsMd).toContain('### Rule: no-attribution');
      expect(agentsMd).toContain('embed the workspace');
      expect(agentsMd).toContain('output_schema');
      expect(agentsMd).not.toContain('automatically exclude context files');
      expect(agentsMd).toContain('<!-- aiwg-managed -->');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('emits no .hermes.md twin and removes a managed twin from a prior deploy', async () => {
    const dir = makeTmpDir();
    try {
      seedProject(dir);
      // Managed twin written by the pre-alignment pipeline (aiwg-managed signature)
      writeFileSync(join(dir, '.hermes.md'), '# AGENTS.md\n<!-- aiwg-managed -->\n<!-- Generated by AIWG. Edit AGENTS.override.md for operator additions. -->\n\nbootstrap stub\n', 'utf8');
      const result = await generate({ provider: 'hermes', projectPath: dir, sections: [], detectExistingFiles: true });
      expect(existsSync(join(dir, '.hermes.md'))).toBe(false);
      expect(result.warnings.some((w) => w.includes('.hermes.md'))).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('removes a stale AIWG thin pointer (pre-alignment hermes.mjs output)', async () => {
    const dir = makeTmpDir();
    try {
      seedProject(dir);
      writeFileSync(join(dir, '.hermes.md'), '# Hermes Routing\n\nAIWG project context lives in `AGENTS.md` (this file is a thin Hermes pointer).\n\n**Routing**: see `AGENTS.md` in this directory.\n', 'utf8');
      await generate({ provider: 'hermes', projectPath: dir, sections: [], detectExistingFiles: true });
      expect(existsSync(join(dir, '.hermes.md'))).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('preserves an operator-authored .hermes.md', async () => {
    const dir = makeTmpDir();
    try {
      seedProject(dir);
      const userBody = '# My project notes\n\nHand-written operator context — must survive regenerates.\n';
      writeFileSync(join(dir, '.hermes.md'), userBody, 'utf8');
      await generate({ provider: 'hermes', projectPath: dir, sections: [], detectExistingFiles: true });
      expect(readFileSync(join(dir, '.hermes.md'), 'utf8')).toBe(userBody);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('hermes.mjs text sync (single source of truth enforced by test)', () => {
  const hermesMjs = readFileSync(join(REPO_ROOT, 'tools/agents/providers/hermes.mjs'), 'utf8');

  function extractTemplate(name: string): string {
    const marker = `const ${name} = \``;
    const start = hermesMjs.indexOf(marker);
    expect(start, `${name} not found in hermes.mjs`).toBeGreaterThan(-1);
    const end = hermesMjs.indexOf('`;', start + marker.length);
    const text = hermesMjs.slice(start + marker.length, end);
    // Unescape the template-literal escapes the same way Node would.
    return text.replace(/\\`/g, '`').replace(/\\\$\{/g, '${');
  }

  it('CRITICAL rule directives match tools/agents/providers/hermes.mjs byte-for-byte', () => {
    const fromMjs = extractTemplate('CRITICAL_RULE_DIRECTIVES');
    expect(fromMjs).toContain('### Rule: ops-safety'); // guards against early truncation
    expect(HERMES_CRITICAL_RULES).toBe(fromMjs);
  });

  it('subagent note matches tools/agents/providers/hermes.mjs byte-for-byte', () => {
    const fromMjs = extractTemplate('HERMES_SUBAGENT_NOTE');
    expect(fromMjs).toContain('output_schema');
    expect(HERMES_SUBAGENT_NOTE).toBe(fromMjs);
  });
});
