/**
 * Embedded source of the isolated provider host (gates P1).
 *
 * The parent (`loader.ts`) writes this verbatim to `<snapshot>/__aiwg_child.mjs`
 * and spawns it as `node --experimental-vm-modules --permission
 * --allow-fs-read=<snapshotDir>`. Keeping the driver as an embedded string (no
 * runtime file read) guarantees the parent and child always run the same
 * driver bytes in every layout (source checkout, tsx, compiled dist).
 *
 * The driver itself is plain dependency-free JavaScript: no template literals
 * and no `${` sequences, so it survives embedding in a TypeScript template
 * literal byte-identically.
 *
 * Security model (see docs/decision/gate-providers.md): the `vm` context is
 * NOT the boundary. The boundary is the child process (permission model: no
 * fs-write, fs-read only for the snapshot dir, no worker/addons/wasi, child
 * process spawn denied) plus the parent's SIGKILL timeout and output caps.
 * The `vm` context is depth: provider code is linked through a tiny loader
 * that serves only relative `.mjs` snapshot files (static specifiers only)
 * and evaluates inside a context stripped of code-generation, I/O, clock and
 * randomness globals.
 */
export const ISOLATED_CHILD_SOURCE = [
  "import fs from 'node:fs';",
  "import path from 'node:path';",
  "import vm from 'node:vm';",
  "import { fileURLToPath } from 'node:url';",
  '',
  'var snapshotDir = path.dirname(fileURLToPath(import.meta.url));',
  'var MAX_RESPONSE_BYTES = 1048576;',
  '',
  'function respond(body) {',
  "  var text = JSON.stringify(body);",
  '  if (typeof text !== \'string\' || Buffer.byteLength(text) > MAX_RESPONSE_BYTES) {',
  "    text = JSON.stringify({ ok: false, error: 'isolated provider response exceeds the output cap' });",
  '  }',
  "  process.stdout.write(text + '\\n', function () { process.exit(0); });",
  '}',
  "function refuse(message) { respond({ ok: false, error: String(message).slice(0, 2000) }); }",
  "process.on('uncaughtException', function (error) {",
  "  refuse('isolated provider crashed: ' + ((error && error.message) || 'unknown'));",
  '});',
  '',
  'function main() {',
  '  var request;',
  '  try {',
  "    request = JSON.parse(fs.readFileSync(path.join(snapshotDir, '__aiwg_request.json'), 'utf8'));",
  '  } catch (e) { refuse(\'isolated provider request is unreadable\'); return; }',
  "  if (!request || typeof request !== 'object' || Array.isArray(request)) { refuse('isolated provider request is invalid'); return; }",
  "  var entry = request.entry;",
  "  var files = request.files;",
  "  var mode = request.mode;",
  "  if (typeof entry !== 'string' || !entry || Array.isArray(files) === false) { refuse('isolated provider request is invalid'); return; }",
  "  if (mode !== 'inspect' && mode !== 'invoke') { refuse('isolated provider request is invalid'); return; }",
  "  if (typeof request.clockMs !== 'number' || !Number.isSafeInteger(request.clockMs)) { refuse('isolated clock is invalid'); return; }",
  "  if (typeof request.seed !== 'number' || !Number.isSafeInteger(request.seed) || request.seed < 0) { refuse('isolated seed is invalid'); return; }",
  "  if (mode === 'invoke' && typeof request.recordsJson !== 'string') { refuse('isolated provider records are invalid'); return; }",
  "  if (typeof request.expectedId !== 'string' || !request.expectedId || typeof request.expectedVersion !== 'string' || !request.expectedVersion) { refuse('isolated provider request is invalid'); return; }",
  '',
  '  var bootstrap = [',
  "    '\\'use strict\\';',",
  "    'var FORBIDDEN = [\\'eval\\', \\'Function\\', \\'WebAssembly\\', \\'Proxy\\', \\'Reflect\\', \\'console\\', \\'Intl\\', \\'Atomics\\', \\'SharedArrayBuffer\\', \\'FinalizationRegistry\\', \\'WeakRef\\', \\'AsyncDisposableStack\\', \\'DisposableStack\\', \\'SuppressedError\\', \\'Iterator\\'];',",
  '    \'for (var i = 0; i < FORBIDDEN.length; i++) {\',',
  '    \'  var name = FORBIDDEN[i];\',',
  '    \'  try { delete globalThis[name]; } catch (e) {}\',',
  '    "  if (typeof globalThis[name] !== \'undefined\') { try { globalThis[name] = undefined; } catch (e) {} }",',
  "    '  if (typeof globalThis[name] !== \\'undefined\\') throw new Error(\\'isolated context retains \\' + name);',",
  '    \'}\',',
  '    \'try { delete Math.random; } catch (e) {}\',',
  "    'if (typeof Math.random !== \\'undefined\\') { try { Math.random = undefined; } catch (e) {} }',",
  "    'if (typeof Math.random !== \\'undefined\\') throw new Error(\\'isolated context retains Math.random\\');',",
  '    \'var FROZEN_MS = globalThis.__aiwgClockMs;\',',
  "    'if (typeof FROZEN_MS !== \\'number\\' || !Number.isSafeInteger(FROZEN_MS)) throw new Error(\\'isolated clock is invalid\\');',",
  '    \'class FrozenDate extends Date {\',',
  '    \'  constructor(...args) { if (args.length === 0) super(FROZEN_MS); else super(...args); }\',',
  '    \'  static now() { return FROZEN_MS; }\',',
  '    \'}\',',
  '    \'globalThis.Date = FrozenDate;\',',
  '    \'globalThis.clock = FROZEN_MS;\',',
  '    \'var __state = (globalThis.__aiwgSeed >>> 0) || 1;\',',
  '    \'globalThis.random = function () {\',',
  '    \'  __state = (__state + 0x6D2B79F5) >>> 0;\',',
  '    \'  var t = __state;\',',
  '    \'  t = Math.imul(t ^ (t >>> 15), t | 1);\',',
  '    \'  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);\',',
  '    \'  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;\',',
  '    \'};\',',
  "    'if (typeof globalThis.__aiwgRecordsJson !== \\'undefined\\') {',",
  '    \'  var parsedRecords = JSON.parse(globalThis.__aiwgRecordsJson);\',',
  '    \'  var freezeDeep = function (value) {\',',
  "    '    if (value && typeof value === \\'object\\') {',",
  '    \'      var keys = Object.keys(value);\',',
  '    \'      for (var k = 0; k < keys.length; k++) freezeDeep(value[keys[k]]);\',',
  '    \'      Object.freeze(value);\',',
  '    \'    }\',',
  '    \'    return value;\',',
  '    \'  };\',',
  '    \'  globalThis.__aiwgRecords = freezeDeep(parsedRecords);\',',
  '    \'}\',',
  '    \'delete globalThis.__aiwgSeed;\',',
  '    \'delete globalThis.__aiwgClockMs;\',',
  '    \'delete globalThis.__aiwgRecordsJson;\',',
  '  ].join("\\n");',
  '',
  '  var context = vm.createContext(Object.create(null));',
  '  context.__aiwgSeed = request.seed >>> 0;',
  '  context.__aiwgClockMs = request.clockMs;',
  "  if (mode === 'invoke') context.__aiwgRecordsJson = request.recordsJson;",
  '  try {',
  "    vm.runInContext(bootstrap, context, { filename: '__aiwg_bootstrap.mjs' });",
  '  } catch (e) { refuse(\'isolated context setup failed: \' + (e && e.message)); return; }',
  '',
  '  var allowed = new Set();',
  '  for (var f = 0; f < files.length; f++) { if (typeof files[f] === \'string\') allowed.add(files[f]); }',
  '  var cache = new Map();',
  '',
  '  function stripModule(code, rel) {',
  '    var failScan = function (why) { throw new Error(\'provider module cannot be scanned: \' + rel + \': \' + why); };',
  '    var n = code.length;',
  '    var kept = [];',
  '    var pos = 0;',
  '    var push = function (ch) { kept.push(ch); };',
  '    var skipLine = function () { while (pos < n && code[pos] !== "\\n") { push(" "); pos++; } };',
  '    var skipBlock = function () {',
  '      push(" "); push(" "); pos += 2;',
  '      var closed = false;',
  '      while (pos < n) {',
  '        if (code[pos] === "*" && code[pos + 1] === "/") { push(" "); push(" "); pos += 2; closed = true; break; }',
  '        push(code[pos] === "\\n" ? "\\n" : " "); pos++;',
  '      }',
  '      if (closed !== true) failScan("unterminated block comment");',
  '    };',
  '    var skipString = function (quote) {',
  '      push(" "); pos++;',
  '      var done = false;',
  '      while (pos < n) {',
  '        var c = code[pos];',
  '        if (c === "\\\\") { push(" "); push(" "); pos += 2; continue; }',
  '        if (c === "\\n") failScan("unterminated string literal");',
  '        if (c === quote) { push(" "); pos++; done = true; break; }',
  '        push(" "); pos++;',
  '      }',
  '      if (done !== true) failScan("unterminated string literal");',
  '    };',
  '    var scanBrace = function () {',
  '      var depth = 1;',
  '      while (pos < n && depth > 0) {',
  '        var c = code[pos];',
  '        if (c === "{") { push(c); depth++; pos++; continue; }',
  '        if (c === "}") { depth--; push(depth === 0 ? " " : c); pos++; continue; }',
  '        if (c === "/" && code[pos + 1] === "/") { skipLine(); continue; }',
  '        if (c === "/" && code[pos + 1] === "*") { skipBlock(); continue; }',
  "        if (c === \'\\\'\' || c === \'" + '"' + "\') { skipString(c); continue; }",
  '        if (c === "`") { skipTemplate(); continue; }',
  '        push(c); pos++;',
  '      }',
  '      if (depth !== 0) failScan("unterminated substitution");',
  '    };',
  '    var skipTemplate = function () {',
  '      push(" "); pos++;',
  '      while (pos < n) {',
  '        var c = code[pos];',
  '        if (c === "\\\\") { push(" "); push(" "); pos += 2; continue; }',
  '        if (c === "`") { push(" "); pos++; return; }',
  '        if (c === "$" && code[pos + 1] === "{") { push(" "); push(" "); pos += 2; scanBrace(); continue; }',
  '        push(c === "\\n" ? "\\n" : " "); pos++;',
  '      }',
  '      failScan("unterminated template literal");',
  '    };',
  '    if (code.slice(0, 2) === "#!") { while (pos < n && code[pos] !== "\\n") { push(" "); pos++; } }',
  '    while (pos < n) {',
  '      var ch = code[pos];',
  '      if (ch === "/" && code[pos + 1] === "/") { skipLine(); continue; }',
  '      if (ch === "/" && code[pos + 1] === "*") { skipBlock(); continue; }',
  "      if (ch === \'\\\'\' || ch === \'" + '"' + "\') { skipString(ch); continue; }",
  '      if (ch === "`") { skipTemplate(); continue; }',
  '      push(ch); pos++;',
  '    }',
  '    return kept.join("");',
  '  }',
  '',
  '  function forbidDynamic(cleaned, rel) {',
  '    var pattern = /(^|[^.$\\w])(import|require)(\\s*)(\\(|\\.)?/g;',
  '    var match = null;',
  '    while ((match = pattern.exec(cleaned)) !== null) {',
  '      var keyword = match[2];',
  '      var punct = match[4];',
  "      if (keyword === 'import' && punct === '(') throw new Error('dynamic import() is forbidden in ' + rel + ': use static relative imports');",
  "      if (keyword === 'require' && punct === '(') throw new Error('require() is forbidden in ' + rel + ': use static relative imports');",
  '    }',
  '  }',
  '',
  '  function childLink(specifier, parentRel) {',
  "    if (typeof specifier !== 'string' || (specifier.startsWith('./') !== true && specifier.startsWith('../') !== true)) {",
  "      throw new Error('bare and external imports are forbidden in phase 1: ' + specifier);",
  '    }',
  "    var base = parentRel ? parentRel.slice(0, parentRel.lastIndexOf('/') + 1) : '';",
  "    var parts = (base + specifier).split('/');",
  '    var out = [];',
  '    for (var i = 0; i < parts.length; i++) {',
  "      if (parts[i] === '' || parts[i] === '.') continue;",
  "      if (parts[i] === '..') {",
  '        if (out.length === 0) throw new Error(\'provider import escapes the snapshot: \' + specifier);',
  '        out.pop();',
  '      } else out.push(parts[i]);',
  '    }',
  "    var rel = out.join('/');",
  "    if (rel.endsWith('.mjs') !== true) throw new Error('provider modules must be relative .mjs files: ' + specifier);",
  "    if (rel === '__aiwg_child.mjs' || rel === '__aiwg_request.json' || rel.indexOf('__aiwg_') === 0 || rel.indexOf('/__aiwg_') !== -1) {",
  "      throw new Error('provider module is reserved: ' + specifier);",
  '    }',
  "    if (allowed.has(rel) !== true) throw new Error('provider module is not in the pinned snapshot: ' + specifier);",
  '    return rel;',
  '  }',
  '',
  '  async function getModule(rel) {',
  '    if (cache.has(rel)) return cache.get(rel);',
  '    var code;',
  '    try {',
  "      code = fs.readFileSync(path.join(snapshotDir, rel), 'utf8');",
  "    } catch (e) { throw new Error('provider module is unreadable: ' + rel); }",
  '    var mod = new vm.SourceTextModule(code, {',
  '      identifier: rel,',
  '      context: context,',
  "      importModuleDynamically: function () { throw new Error('dynamic import() is forbidden: use static relative imports'); },",
  '    });',
  '    cache.set(rel, mod);',
  '    try {',
  '      await mod.link(async function (specifier) { return getModule(childLink(specifier, rel)); });',
  '    } catch (e) { throw new Error(\'provider import failed for \' + rel + \': \' + (e && e.message)); }',
  '    return mod;',
  '  }',
  '',
  '  async function run() {',
  '    for (var i = 0; i < files.length; i++) {',
  "      if (typeof files[i] !== 'string' || files[i].endsWith('.mjs') !== true) continue;",
  '      var source;',
  '      try {',
  "        source = fs.readFileSync(path.join(snapshotDir, files[i]), 'utf8');",
  "        new vm.SourceTextModule(source, { identifier: files[i], context: context });",
  "      } catch (e) { throw new Error('provider module does not parse: ' + files[i] + ': ' + (e && e.message)); }",
  '      forbidDynamic(stripModule(source, files[i]), files[i]);',
  '    }',
  '    var entryRel = childLink(\'./\' + entry, \'\');',
  '    var entryMod = await getModule(entryRel);',
  '    try {',
  '      await entryMod.evaluate();',
  "    } catch (e) { throw new Error('provider module threw during evaluation: ' + (e && e.message)); }",
  '    var ns = entryMod.namespace;',
  "    var descriptor = (ns && ns.provider) || (ns && ns.default);",
  "    if (!descriptor || typeof descriptor !== 'object') throw new Error('provider module has no provider export');",
  "    if (descriptor.id !== request.expectedId || descriptor.version !== request.expectedVersion) {",
  "      throw new Error('provider module identity does not match its manifest declaration');",
  '    }',
  "    if (typeof descriptor.description !== 'string' || !descriptor.description) throw new Error('provider description is invalid');",
  "    if (!descriptor.metrics || typeof descriptor.metrics !== 'object' || Array.isArray(descriptor.metrics)) {",
  "      throw new Error('provider metrics declaration is invalid');",
  '    }',
  "    if (mode === 'inspect') {",
  '      return { descriptor: JSON.parse(JSON.stringify({',
  '        id: descriptor.id,',
  '        version: descriptor.version,',
  '        description: descriptor.description,',
  '        metrics: descriptor.metrics,',
  '      })) };',
  '    }',
  "    if (typeof descriptor.compute !== 'function') throw new Error('provider compute is not a function');",
  "    var records = vm.runInContext('__aiwgRecords', context);",
  '    var raw = await descriptor.compute(records);',
  "    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('provider returned no metrics');",
  "    if (!raw.metrics || typeof raw.metrics !== 'object') throw new Error('provider returned no metrics');",
  '    return { result: JSON.parse(JSON.stringify(raw)) };',
  '  }',
  '',
  '  run().then(',
  '    function (body) { respond(Object.assign({ ok: true }, body)); },',
  "    function (error) { refuse((error && error.message) || 'isolated provider failed'); },",
  '  );',
  '}',
  '',
  'main();',
].join('\n');
