#!/usr/bin/env python3
# Generated by bin/generate-codex-adapters.py; do not edit.
"""Codex PreToolUse save guard for validated apply_patch Add File headers."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any


FALLBACK_ROOT = Path(__file__).resolve().parents[3]
ADD_PREFIX = "*** Add File: "


def read_payload() -> dict[str, Any]:
    try:
        value = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return {}
    return value if isinstance(value, dict) else {}


def find_project_root(cwd: object) -> Path:
    candidates: list[Path] = []
    if isinstance(cwd, str) and cwd:
        candidate = Path(cwd).expanduser().resolve()
        candidates.extend((candidate, *candidate.parents))
    candidates.append(FALLBACK_ROOT)
    for candidate in candidates:
        if (
            candidate / ".aiwg/addons/pm-os/bin/memory/relocate-into-canonical.sh"
        ).is_file():
            return candidate
    return FALLBACK_ROOT


def engine_redirect(root: Path, source: str) -> Path | None:
    engine = root / ".aiwg/addons/pm-os/bin/memory/relocate-into-canonical.sh"
    try:
        result = subprocess.run(
            [
                "/bin/bash",
                str(engine),
                "--root",
                str(root),
                "--path",
                source,
                "--compute",
                "--json",
            ],
            cwd=root,
            text=True,
            capture_output=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    try:
        value = json.loads(result.stdout.strip().splitlines()[-1])
    except (IndexError, json.JSONDecodeError):
        return None
    if not isinstance(value, dict) or value.get("status") != "redirect":
        return None
    target = value.get("to")
    return Path(target) if isinstance(target, str) and target else None


def safe_relative_target(root: Path, source: str, target: Path) -> tuple[str, Path] | None:
    if not source or source != source.strip() or any(char in source for char in "\r\n\t"):
        return None
    if target.suffix != ".md" or target.name != Path(source).name:
        return None

    work = (root / "📂 Context/Work").resolve()
    try:
        resolved_target = target.resolve(strict=False)
        relative_to_work = resolved_target.relative_to(work)
        relative_to_root = resolved_target.relative_to(root.resolve())
    except (OSError, ValueError):
        return None
    if not relative_to_work.parts or relative_to_work.parts[0] == "..":
        return None
    if resolved_target.exists() or resolved_target.is_symlink():
        return None

    probe = work
    for part in relative_to_work.parent.parts:
        probe = probe / part
        if probe.is_symlink():
            return None
    return relative_to_root.as_posix(), resolved_target


def preserve_newline(original: str, replacement: str) -> str:
    if original.endswith("\r\n"):
        return replacement + "\r\n"
    if original.endswith("\n"):
        return replacement + "\n"
    return replacement


def rewrite_add_headers(root: Path, command: str) -> tuple[str, list[tuple[str, str]]]:
    lines = command.splitlines(keepends=True)
    original_headers: set[str] = set()
    candidates: list[tuple[int, str, str, Path]] = []

    for index, line in enumerate(lines):
        header = line.rstrip("\r\n")
        if not header.startswith(ADD_PREFIX):
            continue
        source = header[len(ADD_PREFIX) :]
        original_headers.add(source.removeprefix("./"))
        target = engine_redirect(root, source)
        if target is None:
            continue
        validated = safe_relative_target(root, source, target)
        if validated is None:
            continue
        relative, absolute = validated
        candidates.append((index, source, relative, absolute))

    if not candidates:
        return command, []

    targets = [item[2] for item in candidates]
    if len(set(targets)) != len(targets):
        return command, []
    for _, source, target, _ in candidates:
        if target in original_headers and target != source.removeprefix("./"):
            return command, []

    applied: list[tuple[str, str]] = []
    for index, source, relative, absolute in candidates:
        try:
            absolute.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
            absolute.parent.resolve().relative_to((root / "📂 Context/Work").resolve())
        except (OSError, ValueError):
            continue
        if absolute.exists() or absolute.is_symlink():
            continue
        lines[index] = preserve_newline(lines[index], ADD_PREFIX + relative)
        applied.append((source, relative))

    return "".join(lines), applied


def main() -> int:
    payload = read_payload()
    if payload.get("tool_name") != "apply_patch":
        return 0
    if payload.get("hook_event_name") not in {None, "PreToolUse"}:
        return 0
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return 0
    command = tool_input.get("command")
    if not isinstance(command, str) or not command:
        return 0

    root = find_project_root(payload.get("cwd"))
    rewritten, mappings = rewrite_add_headers(root, command)
    if not mappings or rewritten == command:
        return 0

    updated_input = dict(tool_input)
    updated_input["command"] = rewritten
    summary = "; ".join(f"{source} -> {target}" for source, target in mappings)
    message = f"[PMOS SAVE GUARD] Redirected new document path(s): {summary}"
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "allow",
                    "permissionDecisionReason": "Validated PMOS canonical-path rewrite.",
                    "updatedInput": updated_input,
                    "additionalContext": message,
                }
            },
            ensure_ascii=False,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
