#!/usr/bin/env python3
# Generated by bin/generate-codex-adapters.py; do not edit.
"""Sequential PMOS SessionStart adapter: tidy wins over daily drip."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any


FALLBACK_ROOT = Path(__file__).resolve().parents[3]


def read_payload() -> dict[str, Any]:
    try:
        value = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return {}
    return value if isinstance(value, dict) else {}


def find_project_root(cwd: object) -> Path:
    candidates: list[Path] = []
    if isinstance(cwd, str) and cwd:
        candidate = Path(cwd).expanduser().resolve()
        candidates.extend((candidate, *candidate.parents))
    candidates.append(FALLBACK_ROOT)
    for candidate in candidates:
        if (
            (candidate / ".aiwg/addons/pm-os/hooks/tidy-reminder.sh").is_file()
            and (candidate / ".aiwg/addons/pm-os/hooks/drip-reminder.sh").is_file()
        ):
            return candidate
    return FALLBACK_ROOT


def extract_context(stdout: str) -> str:
    for raw_line in reversed(stdout.splitlines()):
        line = raw_line.strip()
        if not line:
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(value, dict):
            continue
        direct = value.get("additional_context") or value.get("additionalContext")
        if isinstance(direct, str) and direct.strip():
            return direct.strip()
        specific = value.get("hookSpecificOutput")
        if isinstance(specific, dict):
            nested = specific.get("additionalContext")
            if isinstance(nested, str) and nested.strip():
                return nested.strip()
    return ""


def translate_context(context: str) -> str:
    return context.replace("/daily-drip", "$pm-os-daily-drip").replace(
        "/tidy", "$pm-os-tidy"
    )


def run_reminder(root: Path, filename: str) -> str:
    script = root / ".aiwg/addons/pm-os/hooks" / filename
    try:
        result = subprocess.run(
            ["/bin/bash", str(script)],
            cwd=root,
            text=True,
            capture_output=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    if result.returncode != 0:
        return ""
    return translate_context(extract_context(result.stdout))


def main() -> int:
    payload = read_payload()
    event = payload.get("hook_event_name")
    if event not in {None, "SessionStart"}:
        return 0
    root = find_project_root(payload.get("cwd"))

    # One handler owns both checks so Codex never starts them concurrently.
    context = run_reminder(root, "tidy-reminder.sh")
    if not context:
        context = run_reminder(root, "drip-reminder.sh")
    if not context:
        return 0

    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "SessionStart",
                    "additionalContext": context,
                }
            },
            ensure_ascii=False,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
